version: '3.9'

services:
  postgres-db:
    image: postgres:15beta1
    container_name: postgres-for-go
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data
    networks:
      - default
  go-instance:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.go.dev
    image: go-image
    container_name: go-instance
    ports:
      - "8080:8080"
    volumes:
      - type: bind
        source: ./src
        target: /go-dir
    stdin_open: true
    privileged: true
    depends_on:
      - postgres-db
    networks:
      - default
