version: '3.9'

services:
  maria-db:
    image: mariadb:10.8.3
    container_name: maria-db
    environment:
      - MARIADB_USER=admin
      - MARIADB_PASSWORD=123uoi456
      - MARIADB_DATABASE=wordpress
      - MARIADB_ROOT_PASSWORD=123uoi456
    ports:
      - "3100:3306"
    restart: always
    volumes:
      - type: bind
        source: ./mariadb
        target: /var/lib/mysql
